params {
id = "dfsdfsd"
guide = "sdfsf"
genome = "hg38"
pam = "NGG"
guide_mismatches = "4"
guide_min_pvalue = "0.1"
guard_length = "15"
guard_mismatches = "3"
max_guard_distance = "10"
chr = ""
start = ""
end = ""
strand = ""
}
